### ISSUE TITLE
Suggestion : Some more modules ...

### ISSUE THREAD

**Issue by kerostampcrab** [OMGitzFROST/PlayerLogs#3] opened 2021-12-19 08:32 UTC
Teleportations
Server TPS (A feature for an interval of when to log it)
Server RAM usage (A feature for an interval of when to log it)
Enchantments
The entirety of the full server chat.

Also something neat would be; to log the message a player gets after they ran a command, if any.

**Comment by OMGitzFROST** [comment] 2021-12-20 06:12
Perfect! a few comments though

Teleportations: Do you want to log the location in which they teleported? Or just that they teleported? (this should appear in the cmd log file)
Server RAM usage: will start working on this module, asap for the next update (v1.2)
Enchantments: What are you trying to get logged from this module?
Global Chat: Added in (v1.1) look out for activity.log

**Comment by kerostampcrab** [comment] 2021-12-20 06:14
I guess the place where they had teleported.
I'm not sure about enchantments. I mean they just came to mind for some reason.

**Comment by OMGitzFROST** [comment] 2021-12-20 07:53
Ok will try to add a module for when they use a command like /tp for example it will get their location, but keep in mind this feature will not work as intended all the time because it will only listen for a specific command the command. 

As for enchantments, i will see about adding the cost and the enchantments added, but will let you know if anything changes

**Comment by OMGitzFROST** [comment] 2022-01-30 20:42
Added some new modules, TPS will be in a later version as I am looking for the best way to add this feature, for now enjoy enchantments and ram logging

https://github.com/OMGitzFROST/PlayerLogs/releases/download/v1.2/PlayerLogs-1.2.jar

**Closed by OMGitzFROST** 2022-01-30 20:42 UTC
